#!usr/bin/env python3
# coding:utf-8
#!usr/bin/env python3
# coding:utf-8
import os
from bs4 import BeautifulSoup
import re
import codecs
import pandas as pd
fp=open("北朝鮮を含む記事.txt","w",encoding="utf-8")
path="Desktop/北朝鮮を含む記事"
files=os.listdir(path)

codelist=[]
timelist=[]
ttllist=[]
cttlist=[]

a=os.listdir("Desktop/test file_news")
for file in files:
    if not os.path.isdir(file):
        with codecs.open(path + "/" + file, "r", "utf-8", "ignore") as f:
            tmp = f.read()
            htmldata = BeautifulSoup(tmp, "lxml")
            #date = htmldata.find('span', attrs={'class' : 'date'})
            #datxt=str(date).replace("<span class=\"date\">最終更新:","").replace("</span>","")
            date = htmldata.find("p",attrs={'class' : 'source'})
           # <p class="source">6/19(火) 21:30配信 [0-9]{1,2}:[0-9]{2}配信
            #print(date)
                    #re.sub(r"\((日|月|水|火|木|金|土)\) [0-9]{1,2}:[0-9]{2}","",datxt)
            datt=re.sub(r"\((日|月|水|火|木|金|土)\) [0-9]{1,2}:[0-9]{2}配信","",str(date))
            datt=datt.replace("<p class=\"source\">","").replace("</p>","").replace("\n    ","")
            #print([datt])
            #datt1=re.sub(r"\<p class="source">","",str(datt))
            title = htmldata.find('h1') 
            ttl=str(title).replace("<h1>","").replace("</h1>","").replace("\n","")
           # print(ttl)
            content = htmldata.find_all('p', attrs={'class' : 'ynDetailText'})
            for ct in content:
                ctt=ct.getText()
           # print(ctt)
            codelist.append(file)
            timelist.append(datt)
            ttllist.append(ttl)
            

newstabel= {"A.coder":codelist,"B.time": timelist,"C.headline": ttllist    }
tabel1=pd.DataFrame.from_dict(newstabel)
tabel1.to_csv("samelist.csv",encoding="utf-8",sep=";", index=False)
print("done")
print(tabel1)
